language: node_js
node_js:
  - "node"
  - "4"
  - "6"
  - "lts/*"

jobs:
  include:
    - stage: deploy
      node_js: "6"
    deploy:
      # deploy master to production
      - provider: script
        script: sh $TRAVIS_BUILD_DIR/travis_deploy.sh
        on:
          branch: master